In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [22]:
df = pd.read_csv(r'E:\Machine Learning\Module 12\KNN-Project\Coded_Data.csv')
df

,Unnamed: 0,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10,Result
0,1,53.1,63.4,33.0,46.2,47.3,21.2,44.3,36.1,46.6,65.0,Y
1,2,36.9,54.7,31.1,50.5,56.0,38.9,39.4,56.8,33.0,78.8,N
2,3,41.9,65.5,53.5,52.3,92.5,43.2,94.9,64.7,50.8,67.9,N
3,4,71.7,75.6,37.9,50.5,69.2,52.5,82.3,77.3,80.8,60.9,Y
4,5,74.3,51.8,36.4,40.9,74.7,42.2,65.1,36.2,77.6,74.9,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,58.7,56.4,49.5,38.1,62.8,35.2,43.6,17.9,59.3,71.2,Y
996,997,33.4,52.1,54.7,48.5,85.7,76.2,61.6,40.0,50.8,87.8,N
997,998,66.0,53.6,45.4,56.1,54.6,53.1,22.6,21.8,48.8,73.2,Y
998,999,63.0,47.0,23.6,40.7,97.5,56.6,50.0,59.4,67.7,62.7,Y
999,1000,48.6,52.4,24.2,48.9,56.6,25.5,45.4,50.9,66.7,72.1,Y

In our dataframe, the first column looks like the index, let's set `index_col = 0`

In [3]:
df = df.drop('Unnamed: 0',axis=1)

In [4]:
df

     Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10 Result
0    53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0      Y
1    36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8      N
2    41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9      N
3    71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9      Y
4    74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9      Y
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...
995  58.7  56.4  49.5  38.1  62.8  35.2  43.6  17.9  59.3   71.2      Y
996  33.4  52.1  54.7  48.5  85.7  76.2  61.6  40.0  50.8   87.8      N
997  66.0  53.6  45.4  56.1  54.6  53.1  22.6  21.8  48.8   73.2      Y
998  63.0  47.0  23.6  40.7  97.5  56.6  50.0  59.4  67.7   62.7      Y
999  48.6  52.4  24.2  48.9  56.6  25.5  45.4  50.9  66.7   72.1      Y

[1000 rows x 11 columns]

Great, this looks fine now!<br>

Let's overview the data, we can use `info()` here!

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Cd_1    1000 non-null   float64
 1   Cd_2    1000 non-null   float64
 2   Cd_3    1000 non-null   float64
 3   Cd_4    1000 non-null   float64
 4   Cd_5    1000 non-null   float64
 5   Cd_6    1000 non-null   float64
 6   Cd_7    1000 non-null   float64
 7   Cd_8    1000 non-null   float64
 8   Cd_9    1000 non-null   float64
 9   Cd_10   1000 non-null   float64
 10  Result  1000 non-null   object
dtypes: float64(10), object(1)
memory usage: 86.1+ KB

Let's split the data so that we can fit the `scaler` to the features only!

In [6]:
features = df.drop(columns=['Result'])
features

     Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10
0    53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0
1    36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8
2    41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9
3    71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9
4    74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
995  58.7  56.4  49.5  38.1  62.8  35.2  43.6  17.9  59.3   71.2
996  33.4  52.1  54.7  48.5  85.7  76.2  61.6  40.0  50.8   87.8
997  66.0  53.6  45.4  56.1  54.6  53.1  22.6  21.8  48.8   73.2
998  63.0  47.0  23.6  40.7  97.5  56.6  50.0  59.4  67.7   62.7
999  48.6  52.4  24.2  48.9  56.6  25.5  45.4  50.9  66.7   72.1

[1000 rows x 10 columns]

In [7]:
features

     Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10
0    53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0
1    36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8
2    41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9
3    71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9
4    74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...
995  58.7  56.4  49.5  38.1  62.8  35.2  43.6  17.9  59.3   71.2
996  33.4  52.1  54.7  48.5  85.7  76.2  61.6  40.0  50.8   87.8
997  66.0  53.6  45.4  56.1  54.6  53.1  22.6  21.8  48.8   73.2
998  63.0  47.0  23.6  40.7  97.5  56.6  50.0  59.4  67.7   62.7
999  48.6  52.4  24.2  48.9  56.6  25.5  45.4  50.9  66.7   72.1

[1000 rows x 10 columns]

Let's fit `scaler` to the features now!

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)
print(scaler)

StandardScaler()

So, we have the fitted features to the `scaler` object. We will use this `scaler` object to transform all the features using `.transform()` method in `Scikit-learn` to do the `standardization` job by centering and scaling.<br>
Let's pass the features to `scaler.transform()` to get standardized features in `scaled_features`!

In [9]:
scaled_features = scaler.transform(features)

In [10]:
scaled_features

array([[-0.12252539,  0.1875694 , -0.91183199, ..., -1.48006982,
        -0.95256187, -0.64536551],
       [-1.08602779, -0.43340316, -1.02415132, ..., -0.20055606,
        -1.82621843,  0.6351032 ],
       [-0.78865051,  0.33745933,  0.30003449, ...,  0.28776079,
        -0.68275617, -0.3762815 ],
       ...,
       [ 0.64470801, -0.51191693, -0.17880055, ..., -2.36398512,
        -0.81123508,  0.11549271],
       [ 0.46628164, -0.98299956, -1.46751711, ..., -0.03984418,
         0.40289057, -0.85877696],
       [-0.39016495, -0.59756832, -1.43204784, ..., -0.56524838,
         0.33865112,  0.01342636]])

In [11]:
scaled_features.shape

(1000, 10)

`scaled_features` is a NumPy array, Let's convert this into the pandas `DataFrame`!<br>
We can use our `df.columns` to get the columns name and pass that to `DatFrame()` along with `scaled_features`, note we don't need `Results` column, [:-1] will work *(everything but the last one)*!

In [12]:
#Before Scaling
df

     Cd_1  Cd_2  Cd_3  Cd_4  Cd_5  Cd_6  Cd_7  Cd_8  Cd_9  Cd_10 Result
0    53.1  63.4  33.0  46.2  47.3  21.2  44.3  36.1  46.6   65.0      Y
1    36.9  54.7  31.1  50.5  56.0  38.9  39.4  56.8  33.0   78.8      N
2    41.9  65.5  53.5  52.3  92.5  43.2  94.9  64.7  50.8   67.9      N
3    71.7  75.6  37.9  50.5  69.2  52.5  82.3  77.3  80.8   60.9      Y
4    74.3  51.8  36.4  40.9  74.7  42.2  65.1  36.2  77.6   74.9      Y
..    ...   ...   ...   ...   ...   ...   ...   ...   ...    ...    ...
995  58.7  56.4  49.5  38.1  62.8  35.2  43.6  17.9  59.3   71.2      Y
996  33.4  52.1  54.7  48.5  85.7  76.2  61.6  40.0  50.8   87.8      N
997  66.0  53.6  45.4  56.1  54.6  53.1  22.6  21.8  48.8   73.2      Y
998  63.0  47.0  23.6  40.7  97.5  56.6  50.0  59.4  67.7   62.7      Y
999  48.6  52.4  24.2  48.9  56.6  25.5  45.4  50.9  66.7   72.1      Y

[1000 rows x 11 columns]

In [13]:
cols = df.columns[:-1]
cols

Index(['Cd_1', 'Cd_2', 'Cd_3', 'Cd_4', 'Cd_5', 'Cd_6', 'Cd_7', 'Cd_8', 'Cd_9',
       'Cd_10'],
      dtype='object')

In [14]:
#After Scaling
df_scaled_features = pd.DataFrame(data=scaled_features, columns=cols)#df.columns[:-1])
df_scaled_features

,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10
0,-0.122525,0.187569,-0.911832,0.318653,-1.035516,-2.305940,-0.801865,-1.480070,-0.952562,-0.645366
1,-1.086028,-0.433403,-1.024151,0.624941,-0.445471,-1.153296,-1.131088,-0.200556,-1.826218,0.635103
2,-0.788651,0.337459,0.300034,0.753154,2.030007,-0.873275,2.597862,0.287761,-0.682756,-0.376282
3,0.983718,1.058359,-0.622166,0.624941,0.449771,-0.267648,1.751290,1.066595,1.244427,-1.025795
4,1.138354,-0.640394,-0.710839,-0.058864,0.822788,-0.938396,0.595651,-1.473889,1.038861,0.273232
...,...,...,...,...,...,...,...,...,...,...
995,0.210537,-0.312064,0.063573,-0.258307,0.015714,-1.394244,-0.848897,-2.605053,-0.136721,-0.070082
996,-1.294192,-0.618981,0.370973,0.482481,1.568822,1.275723,0.360492,-1.239002,-0.682756,1.470191
997,0.644708,-0.511917,-0.178801,1.023827,-0.540420,-0.228575,-2.259851,-2.363985,-0.811235,0.115493
998,0.466282,-0.983000,-1.467517,-0.073110,2.369113,-0.000651,-0.418892,-0.039844,0.402891,-0.858777
999,-0.390165,-0.597568,-1.432048,0.510973,-0.404778,-2.025919,-0.727958,-0.565248,0.338651,0.013426

<br>Our data is ready for the Machine Learning part now!
## Let's do the train_test split 
I am sure, you are very comfortable with this now!

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_scaled_features, df['Result'], test_size=0.2, random_state=42)
X_train

,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10
29,1.530892,0.308909,-0.232004,1.216147,0.788877,0.728706,-1.285621,-1.949843,0.756208,0.217559
535,0.157009,0.009129,-0.758132,-0.407890,0.063189,0.044934,1.724414,-0.206737,-0.111025,1.627930
695,0.406806,-0.754596,-0.090127,-1.661532,-0.547203,-1.452853,-0.963117,-0.453986,0.171629,0.069099
557,-1.573727,-0.611844,0.016280,0.190440,0.314128,-1.882653,1.610194,0.825527,-1.061769,-0.385560
836,-0.205791,-0.219275,-0.970947,-1.148678,-1.374622,0.839412,-0.015762,-1.745863,-0.490038,0.059820
...,...,...,...,...,...,...,...,...,...,...
106,-1.978160,0.473074,-0.421174,-1.134432,-0.404778,1.353869,-0.620457,-0.243825,-0.869051,-2.000064
270,0.222432,0.687202,-0.344324,-0.678562,-0.872745,-1.055614,0.703152,-0.509617,1.122372,0.495922
860,-1.026552,1.243937,0.359150,0.218931,1.840107,-0.104845,0.326898,0.133230,-1.511445,0.829957
435,0.888557,0.801404,-0.799513,0.033734,-0.411560,-1.042590,-1.204995,0.071418,-1.350846,0.932023
102,0.983718,1.864909,-1.047797,-0.578841,0.286999,-0.632326,0.501588,-0.379812,-0.233080,-0.283494

In [16]:
X_train

,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10
29,1.530892,0.308909,-0.232004,1.216147,0.788877,0.728706,-1.285621,-1.949843,0.756208,0.217559
535,0.157009,0.009129,-0.758132,-0.407890,0.063189,0.044934,1.724414,-0.206737,-0.111025,1.627930
695,0.406806,-0.754596,-0.090127,-1.661532,-0.547203,-1.452853,-0.963117,-0.453986,0.171629,0.069099
557,-1.573727,-0.611844,0.016280,0.190440,0.314128,-1.882653,1.610194,0.825527,-1.061769,-0.385560
836,-0.205791,-0.219275,-0.970947,-1.148678,-1.374622,0.839412,-0.015762,-1.745863,-0.490038,0.059820
...,...,...,...,...,...,...,...,...,...,...
106,-1.978160,0.473074,-0.421174,-1.134432,-0.404778,1.353869,-0.620457,-0.243825,-0.869051,-2.000064
270,0.222432,0.687202,-0.344324,-0.678562,-0.872745,-1.055614,0.703152,-0.509617,1.122372,0.495922
860,-1.026552,1.243937,0.359150,0.218931,1.840107,-0.104845,0.326898,0.133230,-1.511445,0.829957
435,0.888557,0.801404,-0.799513,0.033734,-0.411560,-1.042590,-1.204995,0.071418,-1.350846,0.932023
102,0.983718,1.864909,-1.047797,-0.578841,0.286999,-0.632326,0.501588,-0.379812,-0.233080,-0.283494

In [17]:
y_train

29     Y
535    Y
695    Y
557    N
836    Y
      ..
106    N
270    Y
860    N
435    Y
102    Y
Name: Result, Length: 800, dtype: object

In [18]:
X_test

,Cd_1,Cd_2,Cd_3,Cd_4,Cd_5,Cd_6,Cd_7,Cd_8,Cd_9,Cd_10
521,-0.842178,1.586542,1.015331,-1.212785,-0.553985,-0.111357,0.420962,0.497922,-0.406527,0.403134
737,1.382204,0.415973,-0.438908,0.575080,-1.489919,-1.062126,-0.848897,-1.838581,0.929654,-0.933007
740,1.269200,0.130468,0.719754,0.959720,-0.364085,0.644048,-2.548761,-0.905216,-0.419374,1.089762
660,0.912348,-0.433403,-1.313817,1.038073,-0.940566,-1.081662,-1.809690,0.572097,0.312955,-0.014410
411,-0.015470,0.737166,0.323681,-0.094479,-0.242007,0.689633,0.508306,-0.206737,-0.181688,2.463019
...,...,...,...,...,...,...,...,...,...,...
408,0.864767,0.415973,-1.047797,-0.500488,0.924520,0.728706,-0.996711,0.800803,1.115948,-1.452618
332,1.269200,-1.618247,-1.183763,0.375637,1.378922,-0.847226,-1.016868,0.627728,0.100965,-0.264936
208,-0.943287,0.194707,1.417316,-0.471996,0.266653,0.865460,-0.983274,1.752711,-1.485749,-0.255658
613,-1.038447,-0.747458,-1.112824,1.729000,1.141548,-1.439829,-0.479362,0.318667,-0.669908,0.885630
78,2.292178,-0.668944,-0.474378,-0.400767,-0.255571,0.298906,-0.136701,-1.640782,0.749784,-0.719596

In [19]:
y_test

521    N
737    Y
740    Y
660    Y
411    N
      ..
408    Y
332    Y
208    N
613    N
78     Y
Name: Result, Length: 200, dtype: object

## KNN
Our focus is to come up with a model that can predict the class in `Result` for the new data point. We don't know what k number will work best, let's start with k = 1 at the moment. <br>
We need to import the `KNeighborsClassifier` from `sklearn.neighbors`.

In [20]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

NeighborsClassifier(n_neighbors=3)
In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.
KNeighborsClassifier
KNeighborsClassifier(n_neighbors=3)

Let's show the score now!

In [21]:
knn.score(X_test, y_test)

0.94